### ISSUE TITLE
screen flashes black when trying to run theia ide from gitpod.io

### ISSUE THREAD

**Issue by rhildred** [FydeOS/chromium-raspberry_pi#1]
This generally works way above my expectations even on a raspberry pi 3 model b. I am not sure whether this is a chromium os or chromium problem.

When I use gitpod.io on my raspberry pi 3 model b and with your https://github.com/FydeOS/chromium_os-raspberry_pi/releases/download/r80/chromiumos_test_image_r80r1-rpi3b.img.xz image my screen flashes black towards the end of it loading. It then comes back to my browser screen and gitpod is there except for the terminal window. I can type in the terminal window and the cursor moves accordingly but nothing is displayed. I was running top (160 mb memory remaining 15% cpu) and I think I had a browser tab on this repo open. I rebooted and I tried again. This time the screen flashed black again but I could see my prompt and what I typed as well as output from `ls` and `pwd`. I made a new folder in the terminal and opened a workspace there succesfully. When I opened a terminal in that workspace the screen flashed black but I could see text in the terminal. When I typed `php --version` the screen went black and when it came back I got the message that chromium had ended unexpectedly asking me if I wanted to restore my pages.

So far this is the most useable ui for raspberry pi 3 model b by far. If I could only use theia on it!!!!

**Comment by fydeos-alpha** [comment]
Please use the [main project](https://github.com/FydeOS/chromium_os-raspberry_pi) for issues and questions.
